In [ ]:
#data jo milta ha wo clean nhi huta usko clean karna ha arrange karn aha aur missing values ko bhi filll karna huta ha
#

In [1]:
#import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data=pd.read_csv('Pictures/Data.csv')

In [5]:
data

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [ ]:
'''independent variable jinko features kahte ha wo alag hoge aur 
label jo dependent variable ha wo alag karn aha '''

In [6]:
'''iloc index location k liye ha 
slicing k liye ha 1st : means sari rows select hogi aur
2nd :-1 means last column nhi lena baqi sare lene ha'''
x=data.iloc[:,:-1].values

#y ma : serows sari aur akhri -1 column jo k label ha hmara
y=data.iloc[:,-1].values

#mager hama values chahiye tu .values lagai uper wali command k sath usse sara kuch array ma ban jaiga

In [7]:
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [8]:
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [12]:
#to fix nan values import SimpleImputer class from sklearn.impute module
#note: missing values jo number ha sirf wo deal hoga is se
from sklearn.impute import SimpleImputer

#SimpleImputer class ha is liye () k sath ha. () ma np.nan ki se bdalna ha usko strategy ma likho 
imputer=SimpleImputer(missing_values=np.nan, strategy='mean')     #nan missing values will be replaced with mean

'''#imputer object k oper uski class ka method aplly kare fit , jidhr fit hoga wha per nan values replace hugi mean se
#1st: se rows sari aur 2nd  1:3 means 1 aur 2 column ayega isma categorical nhi lana hota 
#(1:3 is lower nound include hota ha upper bound nhi measn upper bound se aik kam hi ayega  )'''
imputer.fit(x[:,1:3])                                         #fit sirf means ki calculation karega diye gai columns pe

#z=imputer.transform(x[:,1:3])               # fit wali values dene k transform use karte ha

# x ma hi fit ki calculate values dalega is command se , is k bad nan values nhi rahegi
x[:,1:3]=imputer.transform(x[:,1:3])

In [13]:
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [17]:
#encoding categorical data
#independent variable ko convert karna 

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
'''OneHotEncoder  sirf categorical data pe lagana ha jo 0th colummn ha baqi column passthrough karegeg 
sopehla ct object bna ColumnTransformer class ka phr '''
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])], remainder='passthrough')
x=ct.fit_transform(x)

In [18]:
x

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [ ]:
# jha order matter nhi karta ha waha OneHotEncoder like countries
# aur jha order matter  karta hu wha LabelEncoder lagta ha jaise yes/no.

In [20]:
#dependent variable k liye encoding karni ha
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()                   #isma koi  argument nhi dena 
y=le.fit_transform(y)

In [21]:
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [ ]:
'''pehla splitting karni ha data ki bad ma feature scaling karni ha 
ta k model k pass data k training k doran koi properties ki information na hu'''

In [26]:
#to split data for training and testing
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1)

In [27]:
x_train

array([[0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 35.0, 58000.0]], dtype=object)

In [30]:
y_test

array([0, 1])

In [29]:
x_test

array([[0.0, 1.0, 0.0, 30.0, 54000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [36]:
# feature sccaling har jaga use nhi huti acccording to algorithm use karte ha
#feature scaling do tarha ki ha standardization aur normalization 
#standardization zyada ter use hoti ha iska answer 3 se -3 k dermyan ata ha

from sklearn.preprocessing import StandardScaler
sc=StandardScaler()

#country wala column pehla hi OneHotEncoder pe hu chuka ha us pe apply nnhi karna feature scaling
#0,1,2 yeh column nikal jaiga country k 3 se aga sare feature scale hoga
x_train[:,3:]=sc.fit_transform(x_train[:,3:])   # sirf age aur salary wala column pe apply hogi feature scaling 

In [37]:
x_train    # salary aur age same scale pe agai ha

array([[0.0, 0.0, 1.0, -0.19159184384578545, -1.0781259408412425],
       [0.0, 1.0, 0.0, -0.014117293757057777, -0.07013167641635372],
       [1.0, 0.0, 0.0, 0.566708506533324, 0.633562432710455],
       [0.0, 0.0, 1.0, -0.30453019390224867, -0.30786617274297867],
       [0.0, 0.0, 1.0, -1.9018011447007988, -1.420463615551582],
       [1.0, 0.0, 0.0, 1.1475343068237058, 1.232653363453549],
       [0.0, 1.0, 0.0, 1.4379472069688968, 1.5749910381638885],
       [1.0, 0.0, 0.0, -0.7401495441200351, -0.5646194287757332]],
      dtype=object)

In [39]:
x_test[:,3:]= sc.transform(x_test[:,3:])

In [40]:
x_test

array([[0.0, 1.0, 0.0, -1.4661817944830124, -0.9069571034860727],
       [1.0, 0.0, 0.0, -0.44973664397484414, 0.2056403393225306]],
      dtype=object)