In [10]:
import numpy as np

In [11]:
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])   #list k ander 3 lists ha array() ne us list ko array bnaya
arr2d                                      # wo bhi 3D ma


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
arr2d[0][1]   # 1st row aur 2nd column ka element dega

2

In [13]:
arr2d[1,1]   # 2nd method

5

In [14]:
arr2d[2]   # 3rd row sari ayegi

array([7, 8, 9])

In [19]:
#array ma se specific portion nikalna hu tu

arr2d[:2,1:]    # pahla rows ka btaye phr columns ka btai
#iska matlab ha rows shrow se do lo aur column pehla chor k baqi sare

array([[2, 3],
       [5, 6]])

In [23]:
arr=np.arange(0,10)  # 1D array bnagi 0 se 10 tak
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
cond_arr=arr>5    #conditional array bnagi jo value >7 wo true ha baqi false
cond_arr

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [29]:
arr[cond_arr]   # boolean ma convert ki gai array ko dobara usi array  ma wapis lana k liye sirf 
        # wo jo true value hogi

array([6, 7, 8, 9])

In [30]:
arr[arr<4]   # arr ma 4 se kam values ko nikal kar dega

array([0, 1, 2, 3])

In [36]:
arr2=np.arange(0,50).reshape(5,10)  # 5 rows aur 10 column ma 0 se 50 tal valus adjust karega
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [38]:
arr2[2:,4:]   #rows pehli 2 aur column pehla 4 chorne ha aur baqi sari values deni ha

array([[24, 25, 26, 27, 28, 29],
       [34, 35, 36, 37, 38, 39],
       [44, 45, 46, 47, 48, 49]])

In [39]:
arr2[2:,2:8]  #pehli 2 rows chorega aur column bhi 2 pehla chorega baqi 7 tak rakhaga

array([[22, 23, 24, 25, 26, 27],
       [32, 33, 34, 35, 36, 37],
       [42, 43, 44, 45, 46, 47]])