In [1]:
import numpy as np


In [2]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
ar=np.arange(20,31)
ar

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [4]:
su=ar + arr   # add both arrays
su

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40])

In [6]:
mi=su - arr # subtract both arrays
mi

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [8]:
sca=arr + 100  #add 100 in every element of arr 
sca

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [10]:
arr*arr    #arr k correspponding element aik dosre se multiply hoga

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [11]:
arr/100  #sare elements 100 se divide ho jaiga

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ])

In [12]:
arr/arr  # array ko array se divede kiya ha

C:\Users\AYYAN LAPTOP\AppData\Local\Temp\ipykernel_7152\1862401812.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [13]:
1/arr  # 1 se har eleemnt divide hoga

C:\Users\AYYAN LAPTOP\AppData\Local\Temp\ipykernel_7152\255282349.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [14]:
arr**2  # power 2 ayegi har element ki

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [15]:
np.sqrt(arr)  # aer elemenent ka square root ayega

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [17]:
np.log(arr)    # har element ka log lega

C:\Users\AYYAN LAPTOP\AppData\Local\Temp\ipykernel_7152\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [18]:
np.sin(arr)   #trignometric func lgana k liye

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])