In [4]:
pip install numpy


SyntaxError: invalid syntax (2403565453.py, line 1)

In [5]:
import numpy as np

In [9]:
arr=np.arange(20,31) #20 se 30 tak value hogi
arr


array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [10]:
arr[2]  # index 2 k element ko dega

22

In [14]:
arr[:6]  # start se index 5 tak ki value milagi 6 se aik kam  index tak

array([20, 21, 22, 23, 24, 25])

In [15]:
arr[5:]  #5 se end tak sari values dega array ki

array([25, 26, 27, 28, 29, 30])

In [17]:
#braodcasting
arr[0:5]=92    #pehli 4 values ko 92 aassign kardega
arr

array([92, 92, 92, 92, 92, 25, 26, 27, 28, 29, 30])

In [19]:
arr[8:]=34   #last two values ko 34 assign karega
arr

array([92, 92, 92, 92, 92, 25, 26, 27, 34, 34, 34])

In [21]:
arr_copy=np.copy(arr)  #arr ki copy array bnagi 
arr_copy

array([92, 92, 92, 92, 92, 25, 26, 27, 34, 34, 34])